(async()=>{
  const load=src=>new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=src;script.onload=resolve;script.onerror=reject;document.head.appendChild(script)});
  const modal=document.getElementById('access-modal'),requestForm=document.getElementById('request-form'),requestFeedback=requestForm.querySelector('.request-feedback');
  const openRequest=()=>{document.body.classList.add('modal-open');modal.classList.add('open');modal.scrollTop=0};
  const closeRequest=()=>{modal.classList.remove('open');document.body.classList.remove('modal-open')};
  document.getElementById('request-access').onclick=openRequest;
  document.querySelector('.request-close').onclick=closeRequest;
  modal.onclick=event=>{if(event.target===modal)closeRequest()};
  await load('vendor/supabase-js.min.js');await load('supabase-config.js?v=2');
  const client=supabase.createClient(FT_SUPABASE.url,FT_SUPABASE.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});window.ftSupabase=client;
  const googleButton=document.getElementById('google-login');
  try{const settings=await fetch(FT_SUPABASE.url+'/auth/v1/settings',{headers:{apikey:FT_SUPABASE.publishableKey}}).then(response=>response.json());if(!settings?.external?.google){googleButton.disabled=true;googleButton.textContent='Google · pendiente de activar'}}catch{googleButton.disabled=true}
  const routeUser=async user=>{const {data:profile}=await client.from('profiles').select('role').eq('id',user.id).maybeSingle();if(profile?.role==='trainer'||user.email?.toLowerCase()==='ftienda4@gmail.com'){location.href='admin.html?auth=3';return}let {data:member}=await client.from('clients').select('id').eq('user_id',user.id).maybeSingle();if(!member){const {data:linked}=await client.rpc('link_client_identity');if(linked)member=linked}location.href=member?.id?'cliente.html':'pendiente.html'};
  const {data:{session}}=await client.auth.getSession();if(session)await routeUser(session.user);
  googleButton.onclick=async()=>{const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/'}});if(error)alert('No se pudo iniciar el acceso con Google.')};
  const form=document.getElementById('login-form'),button=form.querySelector('.login-submit'),error=document.createElement('p');error.className='login-error';error.hidden=true;button.before(error);
  form.onsubmit=async event=>{event.preventDefault();error.hidden=true;button.disabled=true;button.textContent='Comprobando acceso…';const email=form.querySelector('input[type="email"]').value.trim().toLowerCase(),password=form.querySelector('input[type="password"]').value;const {data,error:authError}=await client.auth.signInWithPassword({email,password});if(!authError){await routeUser(data.user);return}error.textContent='El correo o la contrasena no son correctos. Si aun no tienes cuenta, pulsa “Solicitar registro”.';error.hidden=false;button.disabled=false;button.textContent='Entrar en mi cuenta →'};
  document.getElementById('recover').onclick=async event=>{event.preventDefault();const email=form.querySelector('input[type="email"]').value.trim();if(!email){error.textContent='Escribe primero tu correo para solicitar un enlace de recuperacion.';error.hidden=false;form.querySelector('input[type="email"]').focus();return}const {error:resetError}=await client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/'});error.textContent=resetError?'No se pudo enviar el correo. Intentalo de nuevo.':'Te hemos enviado un enlace para recuperar el acceso.';error.hidden=false};
  requestForm.onsubmit=async event=>{event.preventDefault();requestFeedback.textContent='';const submit=requestForm.querySelector('[type="submit"]'),fd=new FormData(requestForm);const firstName=String(fd.get('first_name')||'').trim(),lastName=String(fd.get('last_name')||'').trim(),email=String(fd.get('email')||'').trim().toLowerCase(),phone=String(fd.get('phone')||'').replace(/[^0-9+]/g,''),dni=String(fd.get('dni')||'').trim().toUpperCase().replace(/[ -]/g,''),password=String(fd.get('password')||''),confirm=String(fd.get('password_confirm')||'');if(!/^([XYZ]\d{7}|\d{8})[A-Z]$/.test(dni)){requestFeedback.textContent='Introduce un DNI o NIE valido.';return}if(password!==confirm){requestFeedback.textContent='Las contrasenas no coinciden.';return}submit.disabled=true;submit.textContent='Enviando solicitud…';const {error:requestError}=await client.rpc('submit_access_request',{p_first_name:firstName,p_last_name:lastName,p_email:email,p_phone:phone,p_dni:dni,p_source:'web'});if(requestError){requestFeedback.textContent='No se pudo enviar la solicitud. Revisa todos los datos.';submit.disabled=false;submit.textContent='Crear cuenta y solicitar acceso';return}const {error:signupError}=await client.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/',data:{display_name:(firstName+' '+lastName).trim(),given_name:firstName,family_name:lastName,phone,dni}}});if(signupError){requestFeedback.textContent='No se pudo crear la cuenta. Si ya tenias acceso, entra o recupera tu contrasena.';submit.disabled=false;submit.textContent='Crear cuenta y solicitar acceso';return}submit.textContent='Solicitud recibida ✓';location.href='pendiente.html'};
})().catch(()=>{const button=document.querySelector('#login-form .login-submit');if(button){button.disabled=true;button.textContent='Servicio temporalmente no disponible'}});
