const liveEmpty=(title,copy)=>`<div class="card" style="padding:34px;text-align:center"><span class="stat-icon" style="margin:auto">${icons.chart}</span><h2>${title}</h2><p class="muted">${copy}</p></div>`;
pages.dashboard=()=>`<div class="stats" id="live-stats"><div class="card stat-card"><span class="stat-icon">${icons.users}</span><div><p id="dashboard-active-label">CLIENTES ACTIVOS ESTE MES</p><h3>—</h3></div></div><div class="card stat-card"><span class="stat-icon orange">${icons.dumbbell}</span><div><p id="dashboard-routine-label">SESIONES COMPLETADAS ESTE MES</p><h3>—</h3></div></div><div class="card stat-card"><span class="stat-icon purple">${icons.card}</span><div><p id="dashboard-payment-label">PAGOS DEL MES</p><h3>—</h3><small id="dashboard-payment-total"></small></div></div></div><div id="live-dashboard-state">${liveEmpty('Panel preparado','Las cifras apareceran cuando anadas clientes y actividad real.')}</div>`;
pages.routines=()=>`<div class="page-placeholder routine-page-intro"><div class="intro"><div><h2>Biblioteca de rutinas</h2><p class="muted">Crea una rutina, anade sus ejercicios y organizala en una carpeta.</p></div><button class="primary" onclick="openRoutineTemplate()">＋ Nueva rutina</button></div></div>`;
pages.progress=()=>`<div class="page-placeholder"><div class="intro"><div><h2>Seguimiento de progreso</h2><p class="muted">Peso, medidas, grasa corporal y evolucion de fuerza.</p></div></div>${liveEmpty('Sin mediciones todavia','Los registros reales de tus clientes apareceran aqui.')}</div>`;
pages.payments=()=>`<div class="page-placeholder"><div class="intro"><div><h2>Pagos en efectivo</h2><p class="muted">Control manual de cuotas y renovaciones.</p></div></div>${liveEmpty('Sin pagos registrados','Registra aqui las cuotas confirmadas en el gimnasio.')}</div>`;
function dashboardPaymentMonth(now=new Date()){
 const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit'}).formatToParts(now),year=Number(parts.find(p=>p.type==='year').value),month=Number(parts.find(p=>p.type==='month').value);
 return {start:`${year}-${String(month).padStart(2,'0')}-01`,end:`${month===12?year+1:year}-${String(month===12?1:month+1).padStart(2,'0')}-01`,label:new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',month:'long',year:'numeric'}).format(now)};
}
function dashboardMadridMidnight(day){
 const target=Date.parse(day+'T00:00:00Z');let timestamp=target;
 const formatter=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});
 for(let i=0;i<3;i++){const parts=Object.fromEntries(formatter.formatToParts(new Date(timestamp)).map(p=>[p.type,p.value]));const represented=Date.parse(`${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}:${parts.second}Z`);timestamp+=target-represented}
 return new Date(timestamp).toISOString();
}
let dashboardPaymentPeriod='';
async function loadDashboardPaymentSummary(){
 const label=document.getElementById('dashboard-payment-label'),total=document.getElementById('dashboard-payment-total');if(!label||!total)return;
 const period=dashboardPaymentMonth();dashboardPaymentPeriod=period.start;label.textContent='PAGOS · '+period.label.toUpperCase();
 let count=0;try{for(let offset=0;;){const {data,error}=await ftSupabase.from('payments').select('id').gte('paid_on',period.start).lt('paid_on',period.end).order('id').range(offset,offset+499);if(error)throw error;if(!data?.length)break;count+=data.length;offset+=data.length}if(!total.isConnected||dashboardPaymentMonth().start!==period.start)return;total.textContent='';total.parentElement.querySelector('h3').textContent=count}catch{total.textContent='No se pudo cargar el resumen';total.parentElement.querySelector('h3').textContent='—'}
}
setInterval(()=>{if(!document.hidden&&document.getElementById('live-stats')&&dashboardPaymentPeriod!==dashboardPaymentMonth().start)loadLiveDashboard()},1000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&document.getElementById('live-stats'))loadLiveDashboard()});
async function loadLiveDashboard(){const stats=document.getElementById('live-stats');if(!stats||!window.ftSupabase)return;const period=dashboardPaymentMonth();const activeLabel=document.getElementById('dashboard-active-label');if(activeLabel)activeLabel.textContent='CLIENTES ACTIVOS · '+period.label.toUpperCase();const routineLabel=document.getElementById('dashboard-routine-label');if(routineLabel)routineLabel.textContent='SESIONES COMPLETADAS · '+period.label.toUpperCase();const results=await Promise.all([ftSupabase.from('clients').select('id',{count:'exact',head:true}).eq('access_status','active'),ftSupabase.from('workout_sessions').select('id',{count:'exact',head:true}).gte('completed_at',dashboardMadridMidnight(period.start)).lt('completed_at',dashboardMadridMidnight(period.end)),ftSupabase.from('payments').select('id',{count:'exact',head:true}).gte('paid_on',dashboardPaymentMonth().start).lt('paid_on',dashboardPaymentMonth().end)]);stats.querySelectorAll('.stat-card:not(.notification-stat) h3').forEach((el,index)=>el.textContent=results[index].error?'—':results[index].count??0);await loadDashboardPaymentSummary()}
const clientOverlay=document.createElement('div');clientOverlay.className='admin-form-overlay';clientOverlay.id='new-client-overlay';clientOverlay.innerHTML=`<form class="admin-form" id="new-client-form"><button type="button" class="admin-form-close" aria-label="Cerrar">×</button><p class="eyebrow">NUEVO SOCIO</p><h2>Crear ficha de cliente</h2><p>El numero de abonado se genera automaticamente. El acceso queda no activo hasta la confirmacion de Fernando.</p><div class="admin-fields"><label class="wide">Nombre completo<input name="full_name" autocomplete="name" required placeholder="Nombre y apellidos"></label><label>DNI / NIE<input name="dni" required placeholder="12345678Z"></label><label>Telefono<input name="phone" type="tel" required placeholder="600 000 000"></label><label class="wide">Direccion<input name="address" autocomplete="street-address" required></label><label>Fecha de nacimiento<input name="birth_date" type="date" required></label><label>Correo de acceso<input name="email" type="email" placeholder="Opcional"></label><div class="wide terms-box"><b>Condiciones de inscripcion y proteccion de datos</b><button type="button" id="open-terms" class="secondary">Leer condiciones completas</button><label><input name="terms_accepted" type="checkbox" required> He leido y acepto las condiciones, las normas de uso y la politica de proteccion de datos.</label></div><label class="wide"><input name="is_minor" type="checkbox"> Menor de edad</label><div class="wide guardian-fields" hidden><label>Representante legal<input name="guardian_name"></label><label>DNI del representante<input name="guardian_dni"></label></div></div><p class="form-feedback" id="new-client-feedback" aria-live="polite"></p><button class="primary full" type="submit">Guardar cliente</button></form>`;document.body.appendChild(clientOverlay);
const newClientForm=clientOverlay.querySelector('#new-client-form'),feedback=clientOverlay.querySelector('#new-client-feedback');const closeClientForm=()=>{clientOverlay.classList.remove('open');newClientForm.reset();feedback.textContent=''};window.openNewClient=()=>clientOverlay.classList.add('open');clientOverlay.querySelector('.admin-form-close').onclick=closeClientForm;clientOverlay.onclick=e=>{if(e.target===clientOverlay)closeClientForm()};newClientForm.querySelector('[name="is_minor"]').onchange=e=>{newClientForm.querySelector('.guardian-fields').hidden=!e.target.checked};newClientForm.querySelector('#open-terms').onclick=()=>alert('Las condiciones completas se incorporaran en el panel legal de FT antes de confirmar el alta.');
newClientForm.onsubmit=async event=>{event.preventDefault();const button=newClientForm.querySelector('[type="submit"]');const data=new FormData(newClientForm);const {data:{user}}=await ftSupabase.auth.getUser();const fullName=String(data.get('full_name')||'').trim().replace(/\s+/g,' '),parts=fullName.split(' '),dni=String(data.get('dni')||'').trim().toUpperCase().replace(/[ -]/g,''),birthDate=String(data.get('birth_date')||''),phone=String(data.get('phone')||'').trim().replace(/[^0-9+]/g,''),today=new Date().toISOString().slice(0,10);button.disabled=true;button.textContent='Guardando…';feedback.textContent='';if(!fullName||!dni||!birthDate||birthDate>today||!phone||!/^([XYZ]\d{7}|\d{8})[A-Z]$/.test(dni)){feedback.textContent='Revisa nombre, DNI/NIE, fecha de nacimiento y telefono.';button.disabled=false;button.textContent='Guardar cliente';return}const email=String(data.get('email')||'').trim().toLowerCase()||`sin-correo-${Date.now()}@ft-trainer.local`;const {data:existing}=await ftSupabase.from('clients').select('id').or(`dni.eq.${dni},phone.eq.${phone}`).maybeSingle();if(existing){feedback.textContent='Ya existe un cliente con ese DNI o telefono.';button.disabled=false;button.textContent='Guardar cliente';return}const record={first_name:parts.shift(),last_name:parts.join(' '),full_name:fullName,dni,address:String(data.get('address')||'').trim(),birth_date:birthDate,email,phone,terms_accepted:true,terms_accepted_at:new Date().toISOString(),terms_version:'FT-2026-01',terms_accepted_by:user?.id||null,guardian_name:String(data.get('guardian_name')||'').trim()||null,guardian_dni:String(data.get('guardian_dni')||'').trim().toUpperCase()||null,access_status:'pending',created_by:user?.id||null};const {error}=await ftSupabase.from('clients').insert(record);button.disabled=false;button.textContent='Guardar cliente';if(error){feedback.textContent=error.code==='23505'?'Ya existe un DNI/NIE o abonado con ese valor.':'No se pudo guardar el cliente. Revisa los datos.';return}closeClientForm();render('clients');toast('Cliente creado correctamente')};
const baseRender=render;render=function(page='dashboard'){baseRender(page);if(page==='dashboard')loadLiveDashboard();if(page==='clients')setTimeout(()=>{window.loadAccessRequests?.();window.loadSupabaseClients?.()},0)};document.getElementById('new-client').onclick=openNewClient;render('dashboard');
