let ftExercises=[];
const catalogTranslations={target:{abs:'Abdominales',pectorals:'Pectoral',biceps:'Bíceps',triceps:'Tríceps',glutes:'Glúteos',quads:'Cuádriceps',hamstrings:'Isquiotibiales',lats:'Dorsales',delts:'Deltoides',calves:'Gemelos'},names:{'barbell bench press':'Press de banca con barra','barbell full squat':'Sentadilla profunda con barra','barbell deadlift':'Peso muerto con barra','pull-up':'Dominadas','dumbbell biceps curl':'Curl de bíceps con mancuernas','dumbbell lateral raise':'Elevaciones laterales con mancuernas'}};
function localizedName(ex){return catalogTranslations.names[ex.nombre.toLowerCase()]||ex.nombre.replace(/barbell/gi,'con barra').replace(/dumbbell/gi,'con mancuerna').replace(/cable/gi,'en polea').replace(/standing/gi,'de pie').replace(/seated/gi,'sentado').replace(/lying/gi,'tumbado').replace(/single arm/gi,'a una mano').replace(/incline/gi,'inclinado');}
function catalogPage(){return `<div class="page-placeholder catalog-page"><div class="intro"><div><h2>Biblioteca de ejercicios</h2><p class="muted"><b>1.324 ejercicios</b> con instrucciones en español, organizados por músculo y material.</p></div><span class="dataset-credit">Datos: exercises-dataset · MIT</span></div><div class="catalog-tools"><label class="catalog-search">${icons.search}<input id="catalog-search" placeholder="Buscar ejercicio, músculo o material..."></label><select id="group-filter"><option value="">Todos los grupos</option>${['Pecho','Espalda','Hombros','Brazos','Piernas','Core','Gemelos','Antebrazos','Cardio','Cuello'].map(x=>`<option>${x}</option>`).join('')}</select><select id="equipment-filter"><option value="">Todo el material</option>${['Peso corporal','Mancuernas','Barra','Polea','Máquina','Banda elástica','Kettlebell'].map(x=>`<option>${x}</option>`).join('')}</select></div><div id="catalog-results" class="catalog-results"><div class="catalog-loading">Cargando catálogo…</div></div><p class="media-notice">Imágenes y animaciones © Gym visual — utilizadas bajo licencia de FT Trainer. Datos e instrucciones bajo licencia MIT.</p></div>`}
async function ensureCatalog(){if(!ftExercises.length){const r=await fetch('data/ejercicios-es.json?v=2');ftExercises=await r.json()}renderCatalog();const q=document.getElementById('catalog-search'),g=document.getElementById('group-filter'),e=document.getElementById('equipment-filter');[q,g,e].forEach(x=>x.addEventListener(x.tagName==='INPUT'?'input':'change',renderCatalog))}
function filteredCatalog(){const q=(document.getElementById('catalog-search')?.value||'').toLowerCase(),g=document.getElementById('group-filter')?.value||'',eq=document.getElementById('equipment-filter')?.value||'';return ftExercises.filter(x=>(!g||x.grupo===g)&&(!eq||x.equipo===eq)&&(!q||`${x.nombre} ${x.grupo} ${x.equipo} ${x.objetivo}`.toLowerCase().includes(q)))}
function renderCatalog(){const all=filteredCatalog(),items=all.slice(0,60);document.getElementById('catalog-results').innerHTML=`<div class="catalog-count">Mostrando <b>${items.length}</b> de <b>${all.length}</b> ejercicios</div><div class="exercise-grid">${items.map(x=>`<article class="card exercise catalog-exercise" data-exercise="${x.id}"><div class="exercise-visual"><img src="${x.imagen}" alt="${localizedName(x)}" loading="lazy"><span>${x.grupo}</span></div><div class="exercise-info"><span class="pill">${x.grupo}</span><h3>${localizedName(x)}</h3><span class="muted">${x.equipo} · ${catalogTranslations.target[x.objetivo]||x.objetivo}</span></div></article>`).join('')}</div>`;document.querySelectorAll('[data-exercise]').forEach(card=>card.onclick=()=>showExercise(card.dataset.exercise))}
function showExercise(id){const x=ftExercises.find(e=>e.id===id),steps=(x.instrucciones||[]).map((s,i)=>`<li><span>${i+1}</span>${s}</li>`).join('');const box=document.createElement('div');box.className='exercise-detail open';box.innerHTML=`<div><button class="detail-close">×</button><div class="detail-layout"><div class="detail-media"><img src="${x.gif}" alt="Demostración de ${localizedName(x)}"><small>${x.atribucion}</small></div><div><span class="pill">${x.grupo} · ${x.equipo}</span><h2>${localizedName(x)}</h2><p class="muted">Objetivo: ${catalogTranslations.target[x.objetivo]||x.objetivo}</p><h4>Ejecución paso a paso</h4><ol>${steps||'<li>Instrucciones en preparación.</li>'}</ol><button class="primary full">＋ Añadir a una rutina</button></div></div></div>`;document.body.appendChild(box);box.querySelector('.detail-close').onclick=()=>box.remove();box.onclick=e=>{if(e.target===box)box.remove()}}
pages.exercises=catalogPage;
document.querySelector('[data-page="exercises"]').addEventListener('click',()=>setTimeout(ensureCatalog));
