let ftExercises=[],catalogOffset=0;
const catalogTranslations={target:{abs:'Abdominales',pectorals:'Pectoral',biceps:'Biceps',triceps:'Triceps',glutes:'Gluteos',quads:'Cuadriceps',hamstrings:'Isquiotibiales',lats:'Dorsales',delts:'Deltoides',calves:'Gemelos',forearms:'Antebrazos',traps:'Trapecios',spine:'Espalda'}};
function localizedName(ex){return ex.nombre_es||ex.nombre}
function normalizeSearch(value){return String(value||'').toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function matchesQuery(haystack,query){const words=normalizeSearch(query).split(/\s+/).filter(Boolean);if(!words.length)return true;const hay=normalizeSearch(haystack);return words.every(word=>hay.includes(word))}
function catalogPage(){return `<div class="page-placeholder catalog-page"><div class="intro"><div><h2>Biblioteca de ejercicios</h2><p class="muted"><b>1.324 ejercicios</b> con instrucciones en espanol, organizados por musculo y material.</p></div><span class="dataset-credit">Datos: exercises-dataset · MIT</span></div><div class="catalog-tools"><label class="catalog-search">${icons.search}<input id="catalog-search" placeholder="Buscar ejercicio, musculo o material..."></label><select id="group-filter"><option value="">Todos los grupos</option>${['Pecho','Espalda','Hombros','Brazos','Piernas','Core','Gemelos','Antebrazos','Cardio','Cuello'].map(x=>`<option>${x}</option>`).join('')}</select><select id="equipment-filter"><option value="">Todo el material</option>${['Peso corporal','Mancuernas','Barra','Polea','Maquina','Banda elastica','Kettlebell'].map(x=>`<option>${x}</option>`).join('')}</select></div><div id="catalog-results" class="catalog-results"><div class="catalog-loading">Cargando catalogo…</div></div><p class="media-notice">Imagenes y animaciones © Gym visual — utilizadas bajo licencia de FT Trainer. Datos e instrucciones bajo licencia MIT.</p></div>`}
async function ensureCatalog(){
 if(!ftExercises.length){const r=await fetch('data/ejercicios-es.json?v=2');ftExercises=await r.json()}
 if(window.ftSupabase){const {data,error}=await ftSupabase.from('exercises').select('id,name,body_group,primary_muscle,equipment,instructions,media_url,media_type,thumbnail_url').eq('is_custom',true).eq('is_active',true).order('name');
 if(!error)ftExercises=[...ftExercises.filter(x=>!x.database),...(data||[]).map(ex=>({id:'custom:'+ex.id,nombre:ex.name,nombre_es:ex.name,grupo:ex.body_group,equipo:ex.equipment||'',objetivo:ex.primary_muscle,imagen:ex.thumbnail_url||'assets/brand/ft-symbol-color.png',instrucciones:(ex.instructions||'').split('\n').filter(Boolean),database:ex}))];
 else toast('No se pudieron cargar los ejercicios propios. Vuelve a abrir la biblioteca.');}
 if(!document.getElementById('catalog-results'))return;
 catalogOffset=0;renderCatalog();const q=document.getElementById('catalog-search'),g=document.getElementById('group-filter'),e=document.getElementById('equipment-filter');[q,g,e].forEach(x=>{x[x.tagName==='INPUT'?'oninput':'onchange']=()=>{catalogOffset=0;renderCatalog()};});
}
function filteredCatalog(){const q=document.getElementById('catalog-search')?.value||'',g=document.getElementById('group-filter')?.value||'',eq=document.getElementById('equipment-filter')?.value||'';return ftExercises.filter(x=>(!g||x.grupo===g)&&(!eq||x.equipo===eq)&&matchesQuery(`${x.nombre_es||''} ${x.nombre} ${x.grupo} ${x.equipo} ${catalogTranslations.target[x.objetivo]||x.objetivo||''} ${(x.musculos||[]).join(' ')}`,q))}
function renderCatalog(){
 const all=filteredCatalog();catalogOffset=Math.min(catalogOffset,Math.max(0,Math.ceil(all.length/60)-1)*60);const items=all.slice(catalogOffset,catalogOffset+60),esc=escapeHtml;
 const pager=()=>`<nav class="catalog-pagination" aria-label="Páginas de ejercicios"><button type="button" data-catalog-step="-1" ${catalogOffset===0?'disabled':''}>← Anterior</button><span>Página ${Math.floor(catalogOffset/60)+1} de ${Math.max(1,Math.ceil(all.length/60))}</span><button type="button" data-catalog-step="1" ${catalogOffset+60>=all.length?'disabled':''}>Siguiente →</button></nav>`;
 document.getElementById('catalog-results').innerHTML=`<div class="catalog-count">Mostrando ${all.length?catalogOffset+1:0}–${catalogOffset+items.length} de <b>${all.length}</b> ejercicios</div>${pager()}<div class="exercise-grid">${items.map(x=>`<article class="card exercise catalog-exercise" data-exercise="${esc(x.id)}"><div class="exercise-visual"><img src="${esc(x.imagen)}" alt="${esc(localizedName(x))}" loading="lazy"><span>${esc(x.grupo)}</span></div><div class="exercise-info"><span class="pill">${esc(x.grupo)}</span><h3>${esc(localizedName(x))}</h3><span class="muted">${esc(x.equipo)} · ${esc(catalogTranslations.target[x.objetivo]||x.objetivo||'')}</span></div></article>`).join('')||'<p>No hay ejercicios con estos filtros.</p>'}</div>${pager()}`;
 document.querySelectorAll('[data-exercise]').forEach(card=>card.onclick=()=>showExercise(card.dataset.exercise));
 document.querySelectorAll('[data-catalog-step]').forEach(button=>button.onclick=()=>{catalogOffset+=Number(button.dataset.catalogStep)*60;renderCatalog();document.getElementById('catalog-results').scrollIntoView({block:'start'});});
}
function showExercise(id){const x=ftExercises.find(e=>e.id===id);if(x?.database){const box=document.createElement('div');box.className='exercise-detail open';box.innerHTML=`<div><button class="detail-close" aria-label="Cerrar">×</button><h2>${escapeHtml(x.nombre)}</h2>${window.ftExerciseMedia.html(x.database)}<p>${escapeHtml(x.database.instructions||'')}</p></div>`;document.body.appendChild(box);box.querySelector('button').onclick=()=>box.remove();box.onclick=e=>{if(e.target===box)box.remove();};return;}const steps=(x.instrucciones||[]).map((s,i)=>`<li><span>${i+1}</span>${s}</li>`).join('');const box=document.createElement('div');box.className='exercise-detail open';box.innerHTML=`<div><button class="detail-close">×</button><div class="detail-layout"><div class="detail-media"><img src="${x.gif}" alt="Demostracion de ${localizedName(x)}"><small>${x.atribucion}</small></div><div><span class="pill">${x.grupo} · ${x.equipo}</span><h2>${localizedName(x)}</h2><p class="muted">Objetivo: ${catalogTranslations.target[x.objetivo]||x.objetivo}</p><h4>Ejecucion paso a paso</h4><ol>${steps||'<li>Instrucciones en preparacion.</li>'}</ol><button class="primary full">＋ Anadir a una rutina</button></div></div></div>`;document.body.appendChild(box);box.querySelector('.detail-close').onclick=()=>box.remove();box.onclick=e=>{if(e.target===box)box.remove()}}
pages.exercises=catalogPage;
document.querySelector('[data-page="exercises"]').addEventListener('click',()=>setTimeout(ensureCatalog));
