const exercises=[
  {name:'Press de banca',detail:'4 series · 8–10 reps · 70 kg',image:'media/images/0025-EIeI8Vf.jpg',gif:'media/videos/0025-EIeI8Vf.gif',tip:'Retrae las escápulas, apoya bien los pies y baja la barra con control hasta el pecho.'},
  {name:'Remo con barra',detail:'4 series · 10 reps · 55 kg',image:'media/images/0027-eZyBC3j.jpg',gif:'media/videos/0027-eZyBC3j.gif',tip:'Mantén la espalda neutra y lleva la barra hacia el abdomen sin balancear el tronco.'},
  {name:'Press inclinado mancuernas',detail:'3 series · 10–12 reps · 24 kg',image:'media/images/0314-ns0SIbU.jpg',gif:'media/videos/0314-ns0SIbU.gif',tip:'Controla la bajada y evita que los hombros se eleven durante el empuje.'},
  {name:'Jalón al pecho',detail:'3 series · 12 reps · 50 kg',image:'media/images/0198-RVwzP10.jpg',gif:'media/videos/0198-RVwzP10.gif',tip:'Inicia el movimiento bajando las escápulas y acerca la barra a la parte alta del pecho.'},
  {name:'Elevaciones laterales',detail:'3 series · 15 reps · 8 kg',image:'media/images/0334-DsgkuIt.jpg',gif:'media/videos/0334-DsgkuIt.gif',tip:'Eleva guiando con los codos y utiliza un peso que te permita evitar el impulso.'},
  {name:'Curl de bíceps',detail:'3 series · 12 reps · 12 kg',image:'media/images/0294-NbVPDMW.jpg',gif:'media/videos/0294-NbVPDMW.gif',tip:'Mantén los codos pegados al cuerpo y controla completamente la fase de bajada.'}
];
let completed=1;
const list=document.getElementById('exercise-list');
list.innerHTML=exercises.map((e,i)=>`<div class="exercise-row ${i===0?'done':''}" data-index="${i}"><span class="exercise-thumb"><img src="${e.image}" alt="${e.name}" loading="lazy"><i>▶</i></span><div><b>${e.name}</b><small>${e.detail}</small><em>Ver técnica y registrar</em></div><strong>${i===0?'✓':'›'}</strong></div>`).join('');
const sheet=document.getElementById('set-sheet'),sheetTitle=document.getElementById('sheet-title');
const media=document.createElement('div');media.className='client-exercise-media';media.innerHTML='<img id="sheet-gif" alt="Demostración del ejercicio"><span>DEMOSTRACIÓN</span><small>© Gym visual</small>';sheetTitle.parentNode.insertBefore(media,sheetTitle);
const technique=document.createElement('p');technique.className='technique-tip';sheetTitle.insertAdjacentElement('afterend',technique);
document.querySelectorAll('.exercise-row').forEach(row=>row.onclick=()=>{const exercise=exercises[row.dataset.index];sheetTitle.textContent=exercise.name;document.getElementById('sheet-gif').src=exercise.gif;document.getElementById('sheet-gif').alt='Demostración de '+exercise.name;technique.textContent=exercise.tip;sheet.dataset.index=row.dataset.index;sheet.classList.add('open')});
document.getElementById('sheet-close').onclick=()=>sheet.classList.remove('open');sheet.onclick=e=>{if(e.target===sheet)sheet.classList.remove('open')};
document.getElementById('save-set').onclick=()=>{const row=document.querySelector(`[data-index="${sheet.dataset.index}"]`);if(!row.classList.contains('done')){row.classList.add('done');row.querySelector('strong').textContent='✓';completed++;const p=Math.round(completed/6*100);document.getElementById('done-count').textContent=completed;document.getElementById('percent').textContent=p+'%';document.getElementById('session-progress').style.width=p+'%'}sheet.classList.remove('open');const t=document.getElementById('client-toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
