const importer={rows:[],headers:[],mapping:{}};
const importFields=[
  ['name','Nombre'],['surname','Apellidos'],['email','Correo'],['phone','Teléfono'],
  ['birthdate','Fecha de nacimiento'],['weight','Peso'],['height','Altura'],
  ['goal','Objetivo'],['experience','Experiencia'],['injuries','Lesiones'],['notes','Observaciones']
];
const aliases={name:['nombre','name'],surname:['apellidos','apellido','surname'],email:['correo','email','correo electronico'],phone:['telefono','movil','phone'],birthdate:['fecha de nacimiento','nacimiento','edad'],weight:['peso','peso kg'],height:['altura','estatura','altura cm'],goal:['objetivo','objetivo principal'],experience:['experiencia','nivel'],injuries:['lesiones','dolencias','patologias'],notes:['observaciones','comentarios','notas']};
const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const overlay=document.createElement('div');overlay.className='import-overlay';overlay.innerHTML=`<section class="import-dialog"><button class="import-close" aria-label="Cerrar">×</button><p class="eyebrow">IMPORTACIÓN DE CLIENTES</p><h2>Traer respuestas de Google Forms</h2><p>Sube el CSV o Excel descargado desde Google Sheets, o pega el enlace de una hoja publicada. Revisarás las columnas antes de incorporar ningún cliente.</p><div class="import-sources"><article class="import-source"><h3>Archivo CSV o Excel</h3><p>Opción recomendada para datos personales. Acepta .csv, .xlsx y .xls y procesa el archivo en este dispositivo.</p><label class="file-drop">Seleccionar archivo<input id="import-file" type="file" accept=".csv,.xlsx,.xls" hidden></label></article><article class="import-source"><h3>Google Sheets</h3><p>Solo para hojas publicadas sin información sensible. La sincronización privada se activará con Google OAuth.</p><div class="sheet-row"><input id="sheet-url" placeholder="https://docs.google.com/spreadsheets/d/..."><button id="load-sheet">Cargar</button></div></article></div><div class="import-status" id="import-status"></div><section class="mapping" id="import-mapping"><h3>Relacionar columnas</h3><p>Hemos detectado automáticamente los campos habituales del formulario. Puedes corregirlos.</p><div class="mapping-grid" id="mapping-grid"></div><div class="import-preview" id="import-preview"></div><div class="import-summary"><span id="import-count"></span><button class="import-confirm" id="import-confirm">Importar clientes</button></div></section></section>`;document.body.appendChild(overlay);
const statusBox=document.getElementById('import-status'),mappingBox=document.getElementById('import-mapping');
function showStatus(message,type='ok'){statusBox.textContent=message;statusBox.className='import-status show '+type}
function detectMapping(){importer.mapping={};importFields.forEach(([key])=>{const found=importer.headers.find(h=>(aliases[key]||[]).some(a=>normalize(h).includes(a)));importer.mapping[key]=found||''})}
function renderMapping(){detectMapping();const options=['<option value="">No importar</option>',...importer.headers.map(h=>`<option value="${String(h).replace(/"/g,'&quot;')}">${h}</option>`)].join('');document.getElementById('mapping-grid').innerHTML=importFields.map(([key,label])=>`<label>${label}<select data-field="${key}">${options}</select></label>`).join('');document.querySelectorAll('#mapping-grid select').forEach(select=>{select.value=importer.mapping[select.dataset.field]||'';select.onchange=()=>{importer.mapping[select.dataset.field]=select.value;renderPreview()}});mappingBox.classList.add('show');renderPreview()}
function renderPreview(){const chosen=importFields.filter(([key])=>importer.mapping[key]);const sample=importer.rows.slice(0,5);document.getElementById('import-preview').innerHTML=`<table><thead><tr>${chosen.map(([,label])=>`<th>${label}</th>`).join('')}</tr></thead><tbody>${sample.map(row=>`<tr>${chosen.map(([key])=>`<td>${row[importer.mapping[key]]??''}</td>`).join('')}</tr>`).join('')}</tbody></table>`;document.getElementById('import-count').textContent=`${importer.rows.length} respuestas encontradas · se muestran las 5 primeras`;document.getElementById('import-confirm').disabled=!importer.mapping.name||!importer.mapping.email}
function acceptRows(rows,source){if(!rows.length)throw new Error('La hoja no contiene respuestas');importer.rows=rows.filter(r=>Object.values(r).some(Boolean));importer.headers=[...new Set(importer.rows.flatMap(Object.keys))];showStatus(`${source}: ${importer.rows.length} respuestas listas para revisar.`);renderMapping()}
async function readFile(file){const data=await file.arrayBuffer();const workbook=XLSX.read(data,{type:'array',cellDates:true});const sheet=workbook.Sheets[workbook.SheetNames[0]];return XLSX.utils.sheet_to_json(sheet,{defval:'',raw:false})}
function googleCsvUrl(value){const match=value.match(/spreadsheets\/d\/([a-zA-Z0-9-_]+)/);if(!match)throw new Error('El enlace de Google Sheets no es válido');const gid=(value.match(/[?&#]gid=(\d+)/)||[])[1]||'0';return `https://docs.google.com/spreadsheets/d/${match[1]}/export?format=csv&gid=${gid}`}
document.getElementById('import-file').onchange=async e=>{try{showStatus('Leyendo el archivo…');acceptRows(await readFile(e.target.files[0]),e.target.files[0].name)}catch(error){showStatus(error.message||'No se pudo leer el archivo','error')}};
document.getElementById('load-sheet').onclick=async()=>{try{showStatus('Conectando con Google Sheets…');const response=await fetch(googleCsvUrl(document.getElementById('sheet-url').value));if(!response.ok)throw new Error('No se pudo abrir la hoja. Comprueba que tenga acceso de lectura por enlace.');const workbook=XLSX.read(await response.arrayBuffer(),{type:'array'});acceptRows(XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{defval:'',raw:false}),'Google Sheets')}catch(error){showStatus(error.message,'error')}};
function syncImportedClients(){const stored=JSON.parse(localStorage.getItem('ft_imported_clients')||'[]');stored.forEach(c=>{const fullName=`${c.name} ${c.surname}`.trim();if(clientStates.some(row=>normalize(row[1])===normalize(fullName)))return;const initials=(c.name.charAt(0)+(c.surname||'').charAt(0)).toUpperCase();clientStates.push([initials,fullName,'Pendiente','—','Pendiente'])})}
document.getElementById('import-confirm').onclick=()=>{const clients=importer.rows.map(row=>Object.fromEntries(importFields.map(([key])=>[key,importer.mapping[key]?row[importer.mapping[key]]:'']))).filter(c=>c.name&&c.email);const stored=JSON.parse(localStorage.getItem('ft_imported_clients')||'[]');const byEmail=new Map(stored.map(c=>[normalize(c.email),c]));clients.forEach(c=>byEmail.set(normalize(c.email),c));localStorage.setItem('ft_imported_clients',JSON.stringify([...byEmail.values()]));syncImportedClients();overlay.classList.remove('open');render('clients');setTimeout(addImportButton);toast(`${clients.length} clientes importados o actualizados`)};
overlay.querySelector('.import-close').onclick=()=>overlay.classList.remove('open');overlay.onclick=e=>{if(e.target===overlay)overlay.classList.remove('open')};
function addImportButton(){const intro=document.querySelector('.page-placeholder .intro');if(!intro||document.getElementById('open-client-import'))return;const actions=document.createElement('div');actions.className='import-actions';actions.innerHTML='<span class="cash-badge">Solo pagos en efectivo</span><button class="import-secondary" id="open-client-import">⇧ Importar CSV / Excel</button>';const old=intro.querySelector('.cash-badge');if(old)old.replaceWith(actions);else intro.appendChild(actions);document.getElementById('open-client-import').onclick=()=>{overlay.classList.add('open');statusBox.className='import-status';mappingBox.classList.remove('show')}}
document.querySelector('[data-page="clients"]').addEventListener('click',()=>setTimeout(addImportButton));
syncImportedClients();
