const accessLabels={active:'Activo',pending:'Pendiente',paused:'No activo'};
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const shortDate=value=>value?new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value)):'—';
const clientState={query:'',status:'all',sort:'subscriber_number',ascending:true,data:[]};
pages.clients=()=>`<div class="page-placeholder"><div class="intro"><div><h2>Clientes y accesos</h2><p class="muted">Ficha de socio, teléfono y estado de acceso.</p></div><span class="cash-badge">Solo pagos en efectivo</span></div><div class="client-toolbar"><label class="search"><span data-icon="search"></span><input id="client-filter" placeholder="Buscar abonado, nombre, DNI o teléfono…"></label><select id="client-status-filter" aria-label="Filtrar por estado"><option value="all">Todos los estados</option><option value="active">Activos</option><option value="paused">No activos</option><option value="pending">Pendientes</option></select></div><div class="card table-card"><table class="table"><thead><tr><th><button class="table-sort" data-sort="subscriber_number">ABONADO ↕</button></th><th><button class="table-sort" data-sort="full_name">NOMBRE ↕</button></th><th><button class="table-sort" data-sort="phone">TELÉFONO ↕</button></th><th><button class="table-sort" data-sort="dni">DNI/NIE ↕</button></th><th><button class="table-sort" data-sort="access_status">ESTADO ↕</button></th><th>ACCIONES</th></tr></thead><tbody id="real-client-rows"><tr><td colspan="6">Cargando clientes…</td></tr></tbody></table></div></div>`;
async function fetchClients(){const result=await ftSupabase.from('clients').select('id,subscriber_number,first_name,last_name,full_name,dni,phone,email,access_status,created_at,terms_accepted,terms_accepted_at').order(clientState.sort,{ascending:clientState.ascending});return result}
function renderClientRows(){const target=document.getElementById('real-client-rows');if(!target)return;let rows=clientState.data.filter(c=>clientState.status==='all'||c.access_status===clientState.status);const q=clientState.query; if(q)rows=rows.filter(c=>[c.subscriber_number,c.full_name,`${c.first_name} ${c.last_name}`,c.dni,c.phone].some(v=>String(v??'').toLowerCase().includes(q)));if(!rows.length){target.innerHTML='<tr><td colspan="6"><b>No hay clientes con estos filtros.</b></td></tr>';return}target.innerHTML=rows.map((client,index)=>{const name=(client.full_name||`${client.first_name} ${client.last_name||''}`).trim();const initials=(name.split(/\s+/).map(x=>x[0]).join('').slice(0,2)).toUpperCase();const active=client.access_status==='active';return `<tr><td><b>#${escapeHtml(client.subscriber_number||'—')}</b></td><td><div class="client-cell"><span class="client-avatar a${index%3+1}">${escapeHtml(initials)}</span><div><b>${escapeHtml(name)}</b><small>${escapeHtml(client.phone||'Sin teléfono')}</small></div></div></td><td>${escapeHtml(client.phone||'—')}</td><td>${escapeHtml(client.dni||'—')}</td><td><span class="status-dot"></span>${accessLabels[client.access_status]||client.access_status}</td><td><button class="activation-btn ${active?'off':''}" onclick="toggleActivation(this,'${client.id}','${client.access_status}')">${active?'Desactivar':'Activar acceso'}</button></td></tr>`}).join('')}
window.loadSupabaseClients=async()=>{const target=document.getElementById('real-client-rows');if(!target)return;const {data,error}=await fetchClients();if(error){target.innerHTML='<tr><td colspan="6">No se pudieron cargar los clientes.</td></tr>';return}clientState.data=data||[];renderClientRows()};
window.toggleActivation=async(button,id,current)=>{button.disabled=true;const next=current==='active'?'paused':'active';const {error}=await ftSupabase.from('clients').update({access_status:next,activated_at:next==='active'?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',id);if(error){button.disabled=false;toast('No se pudo cambiar el acceso');return}toast(next==='active'?'Cliente activado: acceso completo':'Acceso pausado');loadSupabaseClients()};
function bindClientTools(){const filter=document.getElementById('client-filter'),status=document.getElementById('client-status-filter');if(!filter||filter.dataset.bound)return;filter.dataset.bound='1';filter.oninput=()=>{clientState.query=filter.value.trim().toLowerCase();renderClientRows()};status.onchange=()=>{clientState.status=status.value;renderClientRows()};document.querySelectorAll('.table-sort').forEach(button=>button.onclick=()=>{const key=button.dataset.sort;clientState.ascending=clientState.sort===key?!clientState.ascending:true;clientState.sort=key;loadSupabaseClients()})}
const clientPageBase=pages.clients;pages.clients=()=>`<section class="access-request-card card"><div class="section-head"><div><p class="eyebrow">ALTAS DE SOCIOS</p><h2>Solicitudes pendientes</h2></div><span class="cash-badge" id="request-count">Cargando…</span></div><div id="access-request-list"><p class="muted">Consultando solicitudes…</p></div></section>${clientPageBase()}`;
window.loadSupabaseClients=window.loadSupabaseClients;
const oldLoadClients=window.loadSupabaseClients;window.loadSupabaseClients=async()=>{await oldLoadClients();bindClientTools()};
window.loadAccessRequests=async()=>{const target=document.getElementById('access-request-list');if(!target)return;const {data,error}=await ftSupabase.from('access_requests').select('id,first_name,last_name,email,phone,source,status,matched_client_id,conflict_reason,created_at').in('status',['pending','needs_review']).order('created_at',{ascending:false});if(error){target.innerHTML='<p class="muted">No se pudieron cargar las solicitudes.</p>';return}document.getElementById('request-count').textContent=`${data.length} pendiente${data.length===1?'':'s'}`;if(!data.length){target.innerHTML='<div class="request-empty">No hay solicitudes esperando revisión.</div>';return}target.innerHTML=data.map(request=>`<article class="request-row"><div><b>${escapeHtml(`${request.first_name} ${request.last_name}`.trim())}</b><small>${escapeHtml(request.email)}${request.phone?' · '+escapeHtml(request.phone):''}</small><em>${request.matched_client_id?'Coincide con un cliente existente':'Persona nueva'} · ${request.source==='google'?'Google':'Correo'}</em>${request.conflict_reason?`<strong>${escapeHtml(request.conflict_reason)}</strong>`:''}</div><button class="activation-btn" onclick="approveRequest(this,'${request.id}')">Revisar y activar</button></article>`).join('')};
window.approveRequest=async(button,id)=>{button.disabled=true;button.textContent='Activando…';const {error}=await ftSupabase.rpc('approve_access_request',{p_request_id:id,p_client_id:null});if(error){button.disabled=false;button.textContent='Revisar y activar';toast(error.message.includes('identity_conflict')?'Conflicto de cuenta: comprueba el correo':'No se pudo aprobar la solicitud');return}toast('Cuenta unida y acceso activado');await Promise.all([loadAccessRequests(),loadSupabaseClients()])};
document.querySelector('[data-page="clients"]').addEventListener('click',()=>setTimeout(()=>{loadAccessRequests();loadSupabaseClients()},0));
