const accessLabels={active:'Activo',pending:'Pendiente',paused:'No activo'};
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const shortDate=value=>value?new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value)):'—';
const clientState={query:'',status:'all',sort:'subscriber_number',ascending:true,data:[]};
pages.clients=()=>`<div class="page-placeholder"><div class="intro"><div><h2>Clientes y accesos</h2><p class="muted">Ficha de socio, telefono y estado de acceso.</p></div><span class="cash-badge">Solo pagos en efectivo</span></div><div class="client-toolbar"><label class="search"><span data-icon="search"></span><input id="client-filter" placeholder="Buscar abonado, nombre, DNI o telefono…"></label><select id="client-status-filter" aria-label="Filtrar por estado"><option value="all">Todos los estados</option><option value="active">Activos</option><option value="paused">No activos</option><option value="pending">Pendientes</option></select></div><div class="card table-card"><table class="table"><thead><tr><th><button class="table-sort" data-sort="subscriber_number">ABONADO ↕</button></th><th><button class="table-sort" data-sort="full_name">NOMBRE ↕</button></th><th><button class="table-sort" data-sort="phone">TELEFONO ↕</button></th><th><button class="table-sort" data-sort="dni">DNI/NIE ↕</button></th><th><button class="table-sort" data-sort="access_status">ESTADO ↕</button></th><th>ACCIONES</th></tr></thead><tbody id="real-client-rows"><tr><td colspan="6">Cargando clientes…</td></tr></tbody></table></div></div>`;
async function fetchClients(){const result=await ftSupabase.from('clients').select('id,subscriber_number,first_name,last_name,full_name,dni,phone,email,avatar_url,access_status,created_at,terms_accepted,terms_accepted_at').order(clientState.sort,{ascending:clientState.ascending});return result}
function renderClientRows(){const target=document.getElementById('real-client-rows');if(!target)return;let rows=clientState.data.filter(c=>clientState.status==='all'||c.access_status===clientState.status);const q=clientState.query; if(q)rows=rows.filter(c=>[c.subscriber_number,c.full_name,`${c.first_name} ${c.last_name}`,c.dni,c.phone].some(v=>String(v??'').toLowerCase().includes(q)));if(!rows.length){target.innerHTML='<tr><td colspan="6"><b>No hay clientes con estos filtros.</b></td></tr>';return}target.innerHTML=rows.map((client,index)=>{const name=(client.full_name||`${client.first_name} ${client.last_name||''}`).trim();const initials=(name.split(/\s+/).map(x=>x[0]).join('').slice(0,2)).toUpperCase();const active=client.access_status==='active';return `<tr><td><b>#${escapeHtml(client.subscriber_number||'—')}</b></td><td><div class="client-cell"><span class="client-avatar a${index%3+1}">${escapeHtml(initials)}</span><div><b>${escapeHtml(name)}</b><small>${escapeHtml(client.phone||'Sin telefono')}</small></div></div></td><td>${escapeHtml(client.phone||'—')}</td><td>${escapeHtml(client.dni||'—')}</td><td><span class="status-dot"></span>${accessLabels[client.access_status]||client.access_status}</td><td><button class="activation-btn ${active?'off':''}" onclick="toggleActivation(this,'${client.id}','${client.access_status}')">${active?'Desactivar':'Activar acceso'}</button></td></tr>`}).join('')}
window.loadSupabaseClients=async()=>{const target=document.getElementById('real-client-rows');if(!target)return;const {data,error}=await fetchClients();if(error){target.innerHTML='<tr><td colspan="6">No se pudieron cargar los clientes.</td></tr>';return}clientState.data=data||[];renderClientRows()};
window.toggleActivation=async(button,id,current)=>{button.disabled=true;const next=current==='active'?'paused':'active';const {error}=await ftSupabase.from('clients').update({access_status:next,activated_at:next==='active'?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',id);if(error){button.disabled=false;toast('No se pudo cambiar el acceso');return}toast(next==='active'?'Cliente activado: acceso completo':'Acceso pausado');loadSupabaseClients()};
function bindClientTools(){const filter=document.getElementById('client-filter'),status=document.getElementById('client-status-filter');if(!filter||filter.dataset.bound)return;filter.dataset.bound='1';filter.oninput=()=>{clientState.query=filter.value.trim().toLowerCase();renderClientRows()};status.onchange=()=>{clientState.status=status.value;renderClientRows()};document.querySelectorAll('.table-sort').forEach(button=>button.onclick=()=>{const key=button.dataset.sort;clientState.ascending=clientState.sort===key?!clientState.ascending:true;clientState.sort=key;loadSupabaseClients()})}
const clientPageBase=pages.clients;pages.clients=()=>`<details class="access-request-card card" id="access-request-card"><summary><div><p class="eyebrow">ALTAS DE SOCIOS</p><h2>Solicitudes pendientes</h2><small>Abre este bloque para revisar altas nuevas</small></div><span class="request-summary-actions"><span class="cash-badge" id="request-count">Cargando…</span><i aria-hidden="true">⌄</i></span></summary><div class="request-tools"><label><span data-icon="search"></span><input id="request-filter" type="search" placeholder="Buscar solicitud por nombre, DNI, telefono o correo"></label></div><div id="access-request-list"><p class="muted">Consultando solicitudes…</p></div></details>${clientPageBase()}`;
window.loadSupabaseClients=window.loadSupabaseClients;
const oldLoadClients=window.loadSupabaseClients;window.loadSupabaseClients=async()=>{await oldLoadClients();bindClientTools()};
const normalizeIdentity=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const normalizeDni=value=>String(value??'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const normalizePhone=value=>String(value??'').replace(/\D/g,'').replace(/^34(?=\d{9}$)/,'');
let accessRequestState={data:[],query:''};
function findRequestClient(request,clients){const dni=normalizeDni(request.dni),phone=normalizePhone(request.phone),email=String(request.email||'').trim().toLowerCase();if(dni){const match=clients.find(client=>normalizeDni(client.dni)===dni);if(match)return{client:match,method:'DNI/NIE'}}if(phone){const matches=clients.filter(client=>normalizePhone(client.phone)===phone);if(matches.length===1)return{client:matches[0],method:'telefono'}}if(email){const matches=clients.filter(client=>String(client.email||'').trim().toLowerCase()===email);if(matches.length===1)return{client:matches[0],method:'correo'}}return{client:null,method:null}}
function requestDifferences(request,client){if(!client)return[];const requestName=normalizeIdentity(`${request.first_name} ${request.last_name}`),clientName=normalizeIdentity(client.full_name||`${client.first_name||''} ${client.last_name||''}`),differences=[];if(requestName&&clientName&&requestName!==clientName)differences.push('El nombre escrito es diferente');if(request.phone&&client.phone&&normalizePhone(request.phone)!==normalizePhone(client.phone))differences.push('El telefono es diferente');if(request.email&&client.email&&String(request.email).toLowerCase()!==String(client.email).toLowerCase())differences.push('Se actualizara el correo de acceso');return differences}
function renderAccessRequests(){const target=document.getElementById('access-request-list');if(!target)return;let rows=accessRequestState.data;if(accessRequestState.query)rows=rows.filter(({request,match})=>[request.first_name,request.last_name,request.email,request.phone,request.dni,match.client?.full_name,match.client?.dni].some(value=>normalizeIdentity(value).includes(accessRequestState.query)));if(!rows.length){target.innerHTML='<div class="request-empty">No hay solicitudes con esta busqueda.</div>';return}target.innerHTML=rows.map(({request,match,differences})=>{const linked=match.client,linkedName=linked?(linked.full_name||`${linked.first_name||''} ${linked.last_name||''}`).trim():'';return `<article class="request-row"><div class="request-person"><b>${escapeHtml(`${request.first_name} ${request.last_name}`.trim())}</b><small>${escapeHtml(request.email)}${request.phone?' · '+escapeHtml(request.phone):''}${request.dni?' · DNI '+escapeHtml(request.dni):''}</small>${linked?`<em class="request-match">✓ Ficha encontrada por ${escapeHtml(match.method)}: <b>${escapeHtml(linkedName)}</b> · Abonado #${escapeHtml(linked.subscriber_number||'-')}</em>`:'<em class="request-no-match">No se ha encontrado una ficha por DNI, telefono ni correo</em>'}${differences.length?`<strong>${escapeHtml(differences.join(' · '))}</strong>`:''}</div><button class="activation-btn" data-request-id="${request.id}" data-client-id="${linked?.id||''}" ${linked?'':'disabled'}>${linked?'Revisar y activar':'Requiere crear ficha'}</button></article>`}).join('');target.querySelectorAll('[data-request-id]').forEach(button=>button.onclick=()=>approveRequest(button,button.dataset.requestId,button.dataset.clientId))}
window.loadAccessRequests=async()=>{const target=document.getElementById('access-request-list');if(!target)return;const [requestsResult,clientsResult]=await Promise.all([ftSupabase.from('access_requests').select('id,first_name,last_name,email,phone,dni,source,status,matched_client_id,conflict_reason,created_at').in('status',['pending','needs_review']).order('created_at',{ascending:false}),ftSupabase.from('clients').select('id,subscriber_number,first_name,last_name,full_name,dni,phone,email,user_id')]);if(requestsResult.error||clientsResult.error){target.innerHTML='<p class="muted">No se pudieron cargar las solicitudes.</p>';return}const requests=requestsResult.data||[],clients=clientsResult.data||[];accessRequestState.data=requests.map(request=>{const match=findRequestClient(request,clients);return{request,match,differences:requestDifferences(request,match.client)}});document.getElementById('request-count').textContent=`${requests.length} pendiente${requests.length===1?'':'s'}`;if(!requests.length){target.innerHTML='<div class="request-empty">No hay solicitudes esperando revision.</div>';return}renderAccessRequests();const filter=document.getElementById('request-filter');if(filter)filter.oninput=()=>{accessRequestState.query=normalizeIdentity(filter.value);renderAccessRequests()}};
window.approveRequest=async(button,id,clientId)=>{if(!clientId){toast('Primero hay que crear o localizar la ficha del socio');return}const row=accessRequestState.data.find(item=>item.request.id===id),client=row?.match.client;if(!client)return;if(row.differences.length&&!confirm(`La solicitud se unira con ${client.full_name||client.first_name}. ${row.differences.join('. ')}. ¿Continuar?`))return;button.disabled=true;button.textContent='Activando…';const {error}=await ftSupabase.rpc('approve_access_request',{p_request_id:id,p_client_id:clientId});if(error){button.disabled=false;button.textContent='Revisar y activar';toast(error.message.includes('identity_conflict')?'Conflicto de cuenta: esta ficha ya esta vinculada':error.message.includes('email_in_use')?'Ese correo ya pertenece a otra ficha':'No se pudo aprobar la solicitud');return}toast('Cuenta unida con la ficha existente');await Promise.all([loadAccessRequests(),loadSupabaseClients()])};
document.querySelector('[data-page="clients"]').addEventListener('click',()=>setTimeout(()=>{loadAccessRequests();loadSupabaseClients()},0));

function renderClientRows(){
  const target=document.getElementById('real-client-rows');
  if(!target)return;
  let rows=clientState.data.filter(c=>clientState.status==='all'||c.access_status===clientState.status);
  if(clientState.query)rows=rows.filter(c=>[c.subscriber_number,c.full_name,`${c.first_name} ${c.last_name}`,c.dni,c.phone].some(v=>String(v??'').toLowerCase().includes(clientState.query)));
  if(!rows.length){target.innerHTML='<tr><td colspan="6"><b>No hay clientes con estos filtros.</b></td></tr>';return}
  target.innerHTML=rows.map((client,index)=>{
    const name=(client.full_name||`${client.first_name} ${client.last_name||''}`).trim();
    const initials=(name.split(/\s+/).map(x=>x[0]).join('').slice(0,2)).toUpperCase();
    const portrait=client.avatar_url?'':escapeHtml(initials);
    const avatarStyle=client.avatar_url?` style="background-image:url('${escapeHtml(client.avatar_url)}')"`:'';
    const active=client.access_status==='active';
    return `<tr><td><b>#${escapeHtml(client.subscriber_number||'-')}</b></td><td><div class="client-cell"><span class="client-avatar a${index%3+1} ${client.avatar_url?'has-photo':''}"${avatarStyle}>${portrait}</span><div><b>${escapeHtml(name)}</b><small>${escapeHtml(client.phone||'Sin telefono')}</small></div></div></td><td>${escapeHtml(client.phone||'-')}</td><td>${escapeHtml(client.dni||'-')}</td><td><span class="status-dot"></span>${accessLabels[client.access_status]||client.access_status}</td><td><button class="activation-btn ${active?'off':''}" onclick="toggleActivation(this,'${client.id}','${client.access_status}')">${active?'Desactivar':'Activar acceso'}</button></td></tr>`;
  }).join('');
}
